<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<post>
    <author>고상호</author>
    <comments/>
    <content>&#xD;
remote-client-test:&#xD;
    [junit] Running com.informiam.ccat.test.remote.client.RemoteClientTestSuite&#xD;
    [junit] Tests run: 10, Failures: 0, Errors: 10, Time elapsed: 59.609 sec&#xD;
    [junit] Testsuite: com.informiam.ccat.test.remote.client.RemoteClientTestSuite&#xD;
    [junit] Tests run: 10, Failures: 0, Errors: 10, Time elapsed: 59.609 sec&#xD;
    [junit] ------------- Standard Error -----------------&#xD;
    [junit] log4j:WARN No appenders could be found for logger (org.jnp.interfaces.NamingContext).&#xD;
    [junit] log4j:WARN Please initialize the log4j system properly.&#xD;
    [junit] ------------- ---------------- ---------------&#xD;
    [junit] Testcase: testExecuteRules took 6.188 sec&#xD;
    [junit] Caused an ERROR&#xD;
    [junit] Receive timed out&#xD;
    [junit] javax.naming.CommunicationException: Receive timed out [Root exception is java.net.SocketTimeoutException: Receive timed out]&#xD;
    [junit] at org.jnp.interfaces.NamingContext.discoverServer(NamingContext.java:1119)&#xD;
    [junit] at org.jnp.interfaces.NamingContext.checkRef(NamingContext.java:1196)&#xD;
    [junit] at org.jnp.interfaces.NamingContext.lookup(NamingContext.java:516)&#xD;
    [junit] at org.jnp.interfaces.NamingContext.lookup(NamingContext.java:509)&#xD;
    [junit] at javax.naming.InitialContext.lookup(Unknown Source)&#xD;
    [junit] at com.informiam.ccat.service.RuleSessionUtil.lookupHome(Unknown Source)&#xD;
    [junit] at com.informiam.ccat.service.RuleSessionUtil.getHome(Unknown Source)&#xD;
    [junit] at com.informiam.ccat.test.remote.client.RuleSessionTest.setUp(Unknown Source)&#xD;
    [junit] Caused by: java.net.SocketTimeoutException: Receive timed out&#xD;
    [junit] at java.net.PlainDatagramSocketImpl.receive(Native Method)&#xD;
    [junit] at java.net.DatagramSocket.receive(Unknown Source)&#xD;
    [junit] at org.jnp.interfaces.NamingContext.discoverServer(NamingContext.java:1089)&#xD;
    [junit] ... 18 more&#xD;
    [junit] Testcase: testAddRule took 5.922 sec&#xD;
    [junit] Caused an ERROR&#xD;
    [junit] Receive timed out&#xD;
    [junit] javax.naming.CommunicationException: Receive timed out [Root exception is java.net.SocketTimeoutException: Receive timed out]&#xD;
    [junit] at org.jnp.interfaces.NamingContext.discoverServer(NamingContext.java:1119)&#xD;
    [junit] at org.jnp.interfaces.NamingContext.checkRef(NamingContext.java:1196)&#xD;
    [junit] at org.jnp.interfaces.NamingContext.lookup(NamingContext.java:516)&#xD;
    [junit] at org.jnp.interfaces.NamingContext.lookup(NamingContext.java:509)&#xD;
    [junit] at javax.naming.InitialContext.lookup(Unknown Source)&#xD;
    [junit] at com.informiam.ccat.service.RuleSessionUtil.lookupHome(Unknown Source)&#xD;
    [junit] at com.informiam.ccat.service.RuleSessionUtil.getHome(Unknown Source)&#xD;
    [junit] at com.informiam.ccat.test.remote.client.RuleSessionTest.setUp(Unknown Source)&#xD;
    [junit] Caused by: java.net.SocketTimeoutException: Receive timed out&#xD;
    [junit] at java.net.PlainDatagramSocketImpl.receive(Native Method)&#xD;
    [junit] at java.net.DatagramSocket.receive(Unknown Source)&#xD;
    [junit] at org.jnp.interfaces.NamingContext.discoverServer(NamingContext.java:1089)&#xD;
    [junit] ... 18 more</content>
    <postId>EDC76BF8-565F-4181-80F2-E123414286AA</postId>
    <pubDate>2004-08-19T00:00:00-04:00</pubDate>
    <title>the part of error message</title>
</post>
